"""Criar tabelas iniciais

Revision ID: 8cc902f10be8
Revises: 
Create Date: 2026-03-07 07:26:37.893185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc902f10be8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'usuarios',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('senha_hash', sa.String(), nullable=False),
        sa.Column('esta_ativo', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)

    op.create_table(
        'imoveis',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('titulo', sa.String(), nullable=True),
        sa.Column('descricao', sa.String(), nullable=True),
        sa.Column('preco', sa.Float(), nullable=True),
        sa.Column('quartos', sa.Integer(), nullable=True),
        sa.Column('banheiros', sa.Integer(), nullable=True),
        sa.Column('vagas_garagem', sa.Integer(), nullable=True),
        sa.Column('vendido', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imoveis_id'), 'imoveis', ['id'], unique=False)
    op.create_index(op.f('ix_imoveis_titulo'), 'imoveis', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imoveis_titulo'), table_name='imoveis')
    op.drop_index(op.f('ix_imoveis_id'), table_name='imoveis')
    op.drop_table('imoveis')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
